server:
  port: 7000 # puerto del zuul service 
zuul:
  ignoredServices: '*'  
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
      servicio-logpolicia: # Service to create as sample
        path: /zuullog/** #path that will be intercepted
        serviceId: servicio-logpolicia
      servicio-alarmas: # Service to create as sample
        path: /zuulalarma/** #path that will be intercepted
        serviceId: servicio-alarmas
spring:  profiles:    active:      adripriv  application:    name: servidor-zuul